### ISSUE TITLE
Paragraaf 1.5

### ISSUE THREAD

**Issue by jnoev** [bwelman/excelanalyse#1]
De verwijzing naar de website "transfermarkt.nl" in paragraaf 1.5 werkt niet (meer) goed. De tabellen worden niet geladen waardoor de data niet te downloaden is. Dit maakt dat de paragraaf niet goed meer te volgen is.

**Comment by bwelman** [comment]
Probleem wordt onderzocht.

**Comment by bwelman** [comment]
Verwijzing website transfermarkt bijgewerkt met commit b50e366
